### ISSUE TITLE
Nested sections position change

### ISSUE THREAD

**Issue by E-tek** [alikimovich/wrap-in-section#1]
Hi, 
I really like this plugin, use it quite a lot in the last few days
I notice some behavior that I think is not planned or predictable
When using the plugin on a nested section it changes the position inside the parent section
It is not preventing working with the plugin, just wanted to note this.
See attached video: there was a lag in Figma so you can actually see how it jumps out of view :)

Thanks again for developing it

Best regards, 

Eyal Kofman Cagan

https://user-images.githubusercontent.com/1190026/218449663-85253970-2456-4a71-a8f6-63861422ffba.mp4

**Comment by alikimovich** [comment]
Thanks @E-tek !  
It'll be fixed in the next update! At least I'll try to do it 😅

Best,
Andrei

**Comment by alikimovich** [comment]
Hi @E-tek , please check the update!
